# Generated by Django 4.1 on 2022-09-03 15:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('filename', models.CharField(max_length=100)),
                ('addedfiles', models.ImageField(upload_to='files')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
